version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: react_nginx
    volumes:
      - $STATIC_FILE_DIR:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - $HTTPS_PORT:443
      - $PORT:80
    networks:
      - react-mvvm

networks:
  react-mvvm:
    external: false
