name: React-MVVM Simple CI

env:
  VERCEL_ORG_ID: team_slJLmcQUl3ipy2c6JZzgbSjl
  VERCEL_PROJECT_ID: prj_VmFamu49LrfLSMaW6gjSbOrIp54A

on:
  push:
    branches:
      - "staging"
  pull_request:
    branches:
      - "staging"

jobs:
  install_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - name: Setup pnpm
        run: npm install -g pnpm # Ensures pnpm is installed and available

      - name: Install dependencies and build the project
        run: |
          pnpm install
          pnpm build

  deploy:
    if: ${{ github.event.label.name == 'deploy' }}
    needs: install_and_test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@v3

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=7Sn6x76A32wJoZHCuXlHKPQJ

      - name: Build Project Artifacts
        run: vercel build --prod --token=7Sn6x76A32wJoZHCuXlHKPQJ

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=7Sn6x76A32wJoZHCuXlHKPQJ
